const books = [
  {
    bookId: 1,
    bookName: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    rating: 4.8,
    year: 1949,
    borrowedCount: 150,
    available: false,
  },
  {
    bookId: 2,
    bookName: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Fiction",
    rating: 4.3,
    year: 1960,
    borrowedCount: 120,
    available: false,
  },
  {
    bookId: 3,
    bookName: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
    rating: 4.2,
    year: 1925,
    borrowedCount: 200,
    available: true,
  },
  {
    bookId: 4,
    bookName: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    rating: 4.6,
    year: 1813,
    borrowedCount: 180,
    available: true,
  },
  {
    bookId: 5,
    bookName: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Fiction",
    rating: 3.7,
    year: 1951,
    borrowedCount: 160,
    available: false,
  },
  {
    bookId: 6,
    bookName: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
    rating: 4.4,
    year: 1932,
    borrowedCount: 140,
    available: true,
  },
  {
    bookId: 7,
    bookName: "Moby Dick",
    author: "Herman Melville",
    genre: "Adventure",
    rating: 3.9,
    year: 1851,
    borrowedCount: 90,
    available: true,
  },
  {
    bookId: 8,
    bookName: "War and Peace",
    author: "Leo Tolstoy",
    genre: "Historical Fiction",
    rating: 4.5,
    year: 1869,
    borrowedCount: 70,
    available: false,
  },
  {
    bookId: 9,
    bookName: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    rating: 4.7,
    year: 1937,
    borrowedCount: 210,
    available: true,
  },
  {
    bookId: 10,
    bookName: "Fahrenheit 451",
    author: "Ray Bradbury",
    genre: "Dystopian",
    rating: 4.1,
    year: 1953,
    borrowedCount: 130,
    available: false,
  },
  {
    bookId: 11,
    bookName: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    genre: "Philosophical Fiction",
    rating: 4.0,
    year: 1890,
    borrowedCount: 110,
    available: true,
  },
  {
    bookId: 12,
    bookName: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Adventure",
    rating: 4.6,
    year: 1988,
    borrowedCount: 250,
    available: true,
  },
  {
    bookId: 13,
    bookName: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    genre: "Adventure",
    rating: 4.5,
    year: 1844,
    borrowedCount: 80,
    available: false,
  },
  {
    bookId: 14,
    bookName: "The Road",
    author: "Cormac McCarthy",
    genre: "Post-Apocalyptic",
    rating: 4.3,
    year: 2006,
    borrowedCount: 65,
    available: true,
  },
  {
    bookId: 15,
    bookName: "The Handmaid's Tale",
    author: "Margaret Atwood",
    genre: "Dystopian",
    rating: 3.8,
    year: 1985,
    borrowedCount: 175,
    available: false,
  },
];

export default books;
